### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#64]
PHP Runtime Deprecation Notice: The each() function is deprecated. This message will be suppressed on further calls in .../typo3conf/ext/cfc_league_fe/table/football/class.tx_cfcleaguefe_table_football_TableWriter.php line 307

**Comment by digedag** [comment]
Should be fixed.

**Comment by stemeda** [comment]
Error still exists. Typo3 10.4, PHP 7.3, cfc_league_fe 1.5.2, composer mode

**Comment by digedag** [comment]
Sorry, there is still no new release containing this fix. You should use latest HEAD for now.

**Comment by stemeda** [comment]
Sorry for late replay. I've updated to newest compoer version today. I'll check, if error still exists.

**Comment by derhecht** [comment]
obviously solved and closable, isn't it?
